name: Close stale issues
on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-issue-message: |
            Hi folk 😊, it looks like this issue has been inactive for a while. Is there any update or further action
            needed? If not, we might consider closing it soon to keep our board clean and focused.

            But don't worry, you can reopen it anytime when needed.Thank you for your contributions to Kotaemon🪴

          days-before-issue-stale: 30
          days-before-issue-close: 3
          days-before-pr-stale: 90
          days-before-pr-close: -1
          exempt-issue-labels: "documentation,tutorial,TODO"
          operations-per-run: 300 # The maximum number of operations per run, used to control rate limiting.
